language: python

python:
  - 3.7.5

services:
  - mysql

before_install:
  - 'travis_retry sudo apt-get update'
  - 'travis_retry sudo apt-get install xmlsec1'

install: pip install tox-travis

script: tox
