language: node_js

before_script:
 - yes | npm install -g @angular/cli
script:
 # - ng lint
 - npm run test-headless
 - ng build
notifications:
 slack: concentricsky:UugB2sbXyfupEV695xsGm0PH
 email:
  recipients:
   - esletteland@concentricsky.com
  on_success: always
  on_failure: always
